management:
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
spring:
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo
      username: root
      password: rootpassword
      authentication-database: admin
